# Generated by Django 2.2 on 2019-04-04 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20180728_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested',
            name='issue_date',
            field=models.DateField(default=datetime.date(2019, 4, 4)),
        ),
        migrations.AlterField(
            model_name='requested',
            name='return_date',
            field=models.DateField(default=datetime.date(2019, 4, 11)),
        ),
    ]
